version: "3.8"

services:
  app:
    container_name: dev-cv-page
    restart: unless-stopped
    image: dev-cv-page
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
